version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: investment_portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_dev_password
      POSTGRES_DB: investment_portfolio_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio_user -d investment_portfolio_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio_network

  # Redis Cache (for future use with background jobs)
  redis:
    image: redis:7-alpine
    container_name: investment_portfolio_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portfolio_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  portfolio_network:
    driver: bridge
